In [3]:
import numpy as np

In [28]:
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print('arr - ')
print(arr)

print('-------------')

print('shape - ')
print(arr.shape)

print('-------------')

print('size - ')
print(arr.size)

print('-------------')

print('dimension - ')
print(arr.ndim)

arr - 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------------
shape - 
(3, 4)
-------------
size - 
12
-------------
dimension - 
2


In [29]:
print('First row of an array')
arr[1]

First row of an array


array([5, 6, 7, 8])

In [32]:
arr[2][3]

12

In [67]:
l = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [133]:
def ExtractOdd(arr):
    for i in range(len(arr)):
        for j in range(len(arr)+1):
            if j %2!=0:
                print(arr[i][j], end=',')
            


In [134]:
ExtractOdd(arr)

2,4,6,8,10,12,

In [162]:
arr[0:3,[1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [177]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

np.random.randint(0,2, (3,3))

array([[1, 1, 0],
       [1, 0, 1],
       [0, 0, 1]])

In [227]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [228]:
np.expand_dims(arr, axis = 0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [229]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [230]:
matrixA2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
matrixB2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [231]:
matrixA2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [232]:
matrixB2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [233]:
#1. Index wise multiplication


matrixA2 * matrixB2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [234]:
# Matrix multiplication

matrixB3 = matrixB2.reshape(4,3)
matrixA2 @ matrixB3

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [235]:
# Add both the maticx

matrixA2 + matrixB2


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [236]:
#Subtact matix B from matrix A

matrixB2 - matrixA2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [237]:
#Divide matrix B by A

matrixB2 / matrixA2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [244]:
#12. Which function in Numpy can be used to swap the byte order of an array?

print('Before - ')
print(arr)

print()
print('After byt swap - ')
arr2 = arr.byteswap()
arr2

Before - 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

After byt swap - 


array([[ 16777216,  33554432,  50331648,  67108864],
       [ 83886080, 100663296, 117440512, 134217728],
       [150994944, 167772160, 184549376, 201326592]])